Seguros/Controllers/InsuranceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Seguros.DAL;
using System.Web.Mvc;
using Seguros.DAL.Models;

namespace Seguros.Controllers
{
    public class InsuranceController : Controller
    {
        private IInsuranceRepository _insuranceRepository;
        public InsuranceController()
        {
            this._insuranceRepository = new InsuranceRepository(new InsuranceContext());
        }

        public ActionResult Add()
        {
            ViewBag.Title = "Agregar Seguro";

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Insurance insurance)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    this._insuranceRepository.AddInsurance(insurance);
                    this._insuranceRepository.Save();
                    return RedirectToAction("Query");
                }
            }
            catch (Exception ex)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            return View(insurance);
        }

        public ActionResult Details(int? ClientID)
        {
            var insurance = new Seguros.DAL.Models.Insurance();
            if (ClientID != null)
            {
                insurance = _insuranceRepository.GetInsuranceById(ClientID);
            }
            return View(insurance);
        }

        public ActionResult Query()
        {
            var clients = from client in _insuranceRepository.GetAllClients() select client;

            ViewBag.Title = "Consultar Cliente";

            return View(clients);
        }
        public ActionResult Delete()
        {
            ViewBag.Title = "Eliminar Seguro";

            return View();
        }

        public ActionResult Modify()
        {
            ViewBag.Title = "Modificar Seguro";

            return View();
        }


    }
}

Seguros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Seguros", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Consultar", "Query", "Insurance", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Agregar", "Add", "Insurance", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Actualizar", "Modify", "Insurance", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Eliminar", "Delete", "Insurance", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>